config/routes.rb
Rails.application.routes.draw do
  # general page routes
  root 'welcome#index'
  get '/terms', to: 'welcome#terms_and_conditions', as: 'terms'
  get '/privacy', to: 'welcome#privacy_policy', as: 'privacy'
  get '/perfume', to: 'welcome#perfume', as: 'perfume_overview'

  # routes for posts
  resources :posts

  # routes for discovery boxes
  resources :discovery_boxes, path: '/discovery-box'
  post '/discovery-box/:id/perfumes/:perfume_id', to: 'discovery_boxes#add_perfume', as: 'add_perfume'
  delete '/discovery-box/:id/perfumes/:perfume_id', to: 'discovery_boxes#remove_perfume', as: 'remove_perfume'

  # resources for perfumes
  scope '/admin' do
    resources :perfumes
  end

  # other admin routes
  get '/admin', to: 'admin#panel_home', as: 'panel'
  get '/admin/posts', to: 'admin#manage_posts', as: 'manage_posts'
  get '/admin/users', to: 'admin#manage_users', as: 'manage_users'

  # user show page
  get '/users/:id', to: 'users#show', as: 'user'
  post '/users/:id/refer', to: 'users#refer', as: 'refer'

  # devise links for users
  devise_for :users, controllers: {registrations: 'registrations'}, path: '', path_names: { sign_in: 'login', sign_out: 'logout', password: 'password', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: '' }

  # contact form
  resources :contacts, only: [:new, :create]

  # unique registration links
  devise_scope :user do
    get 'register/:id', to: 'registrations#new', as: 'new_referral'
    post 'register/:id', to: 'registrations#create', as: 'create_referral'
  end

  # 404 error
  get '*unmatched_route', to: 'welcome#not_found', as: 'not_found'
end

app/views/shared/_admin-sidebar.html.erb
<div class="admin-sidebar col-12 col-md-4 col-lg-3">
  <div class="space-1"></div>
  <h4 class="bold">
    Admin panel
  </h4>
  <%= link_to "Manage users", manage_users_path %>
  <%= link_to "Manage perfumes", perfumes_path %>
  <%= link_to "New perfume", new_perfume_path %>
  <%= link_to "Manage posts", manage_posts_path %>
  <%= link_to "New post", new_post_path %>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="social purple">
    <ul>
      <li>
        <a href="#" class="hover-transparent">
          <i class="fa fa-snapchat fa-lg"></i>
        </a>
      </li>
      <li>
        <a href="#" class="hover-transparent">
          <i class="fa fa-twitter fa-lg"></i>
        </a>
      </li>
      <li>
        <a href="#" class="hover-transparent">
          <i class="fa fa-facebook fa-lg"></i>
        </a>
      </li>
      <li>
        <a href="#" class="hover-transparent">
          <i class="fa fa-pinterest fa-lg"></i>
        </a>
      </li>
      <li>
        <a href="#" class="hover-transparent">
          <i class="fa fa-instagram fa-lg"></i>
        </a>
      </li>
      <li>
        <a href="#" class="hover-transparent">
          <i class="fa fa-youtube fa-lg"></i>
        </a>
      </li>
    </ul>
  </div>

  <!-- sitemap -->
  <div class="container-fluid">
    <div class="row">
      <div class="col-12 col-md-8">
        <div class="row pad-1">
          <div class="space-1"></div>
          <div class="col-6 col-md-4 footer-links">
            <p class="text-muted bold transparent-text">ACCOUNT</p>
            <ul>
              <% if current_user %>
                <li>
                  <%= link_to "Referrals", user_path(current_user) %>
                </li>
              <% else %>
                <li>
                  <%= link_to "Login", new_user_session_path %>
                </li>
                <li>
                  <%= link_to "Register", new_user_registration_path %>
                </li>
              <% end %>
            </ul>
          </div>

          <div class="col-6 col-md-4 footer-links">
            <p class="text-muted bold transparent-text">ABOUT US</p>
            <ul>
              <li>
                <a href="/posts">
                  Blog
                </a>
              </li>
            </ul>
          </div>

          <div class="col-6 col-md-4 footer-links">
            <p class="text-muted bold transparent-text">HELP</p>
            <ul>
              <li>
                <%= link_to "Contact us", new_contact_path %>
              </li>
            </ul>
          </div>
        </div>
        <!-- close row -->

        <div class="pad-1 hidden-md-down">
          <div class="space-2 hidden-lg-down"></div>
          <p class="transparent-text gray-text small marg-bot-0">
            <%= link_to 'Terms and Conditions', terms_path %> &nbsp; | <%= link_to 'Privacy Policy', privacy_path %> &nbsp; | &nbsp; Copyright &copy; 2017 Love, Sylvie. All rights reserved.
          </p>
        </div>
      </div>
      <!-- close col -->

      <div class="col-12 col-md-4 marg-0 light-gray">
        <div class="space-1"></div>
        <div class="pad-1">
          <p class="text-muted bold">NEWSLETTER</p>
          <p class="gray-text">Stay in touch through our newsletter.</p>
          <% if current_user.nil? %>
            <form id="footer-form" action="index.html" method="post">
              <input type="text" id="footer_email" class="form-control" placeholder="Email..." />
              <button type="footer-submit" name="button" value="submit">
                <i class="fa fa-chevron-right fa"></i>
              </button>
            </form>
          <% end %>
        </div>
        <div class="space-1"></div>
      </div>
      <!-- close col -->
    </div>
    <!-- close row -->
  </div>
  <div class="pad-1 hidden-md-up">
    <p class="transparent-text gray-text small marg-bot-0 center">
      <%= link_to 'Terms and Conditions', terms_path %> &nbsp; | <%= link_to 'Privacy Policy', privacy_path %> &nbsp; | &nbsp; Copyright &copy; 2018 Love, Sylvie. All rights reserved.
    </p>
  </div>
</div>

app/views/shared/_loginModal.html.erb
<div class="modal fade" id="login" tabindex="-1" role="dialog" aria-labelledby="login" aria-hidden="true">
  <div class="space-4"></div>
  <div class="space-4"></div>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <div class="close-wrapper">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
          <h3 class="title">
            Login
          </h3>
          <div class="field marg-bot-1 marg-top-05">
            <%= f.email_field :email, class: 'form-control login-email', required: true, placeholder: "Email" %>
            <i class="fa fa-fw fa-envelope after" aria-hidden="true"></i>
          </div>

          <div class="field">
            <%= f.password_field :password, autocomplete: "off", class: 'form-control login-password', required: true, placeholder: 'Password' %>
            <i class="fa fa-fw fa-unlock after" aria-hidden="true"></i>
          </div>

          <div class="actions">
            <%= f.submit "Log in", class: 'btn btn-purple full-width' %>
          </div>
        <% end %>

        <div class="links">
          Don't have an account? <%= link_to "Register here.", new_user_registration_path %><br />
          <%= link_to "Forgot password?", new_user_password_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<% puts "URL: " + request.path %>
<nav class="navbar navbar-toggleable-md navbar-light bg-faded <%= 'purple' if (request.path != '/') %>">
  <button class="navbar-toggler navbar-toggler-right collapsed" type="button" data-toggle="collapse" data-target="#nav" aria-controls="nav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="icon-bar top-bar"></span>
    <span class="icon-bar middle-bar"></span>
    <span class="icon-bar bottom-bar"></span>
  </button>
  <a class="navbar-brand" href="<%= root_path %>">
    <%= image_tag 'logoWhite.svg' %>
  </a>

  <div class="collapse navbar-collapse" id="nav">
    <!-- <ul class="navbar-nav mr-auto"></ul> -->
    <ul class="navbar-nav ml-auto">
      <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="/">HOME</a>
      </li>
      <li class="nav-item">
        <%= link_to "OUR PERFUME", perfume_overview_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "BLOG", posts_path, class: "nav-link" %>
      </li>
      <% if current_user.nil? %>
        <li class="nav-item">
          <a href="" class="nav-link" data-toggle="modal" data-target="#register">
            REGISTER
          </a>
        </li>
        <li class="nav-item">
          <a href="" class="nav-link" data-toggle="modal" data-target="#login">
            LOGIN
          </a>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "REFERRALS", current_user, class: "nav-link" %>
        </li>
        <% if current_user.isAdmin %>
          <li class="nav-item">
            <%= link_to "ADMIN PANEL", panel_path, class: "nav-link" %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to "LOGOUT", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/shared/_registerModal.html.erb
<div class="modal fade" id="register" tabindex="-1" role="dialog" aria-labelledby="register" aria-hidden="true">
  <div class="space-4"></div>
  <div class="space-4"></div>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <div class="close-wrapper full-width">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { id: "register-form" }) do |f| %>
          <h3 class="title">
            Register
          </h3>

          <%= devise_error_messages! %>

          <div class="field marg-bot-1 marg-top-05">
            <%= f.email_field :email, class: 'form-control register-email', required: true, placeholder: "Email", id: "register-email" %>
            <i class="fa fa-fw fa-envelope after" aria-hidden="true"></i>
          </div>

          <div class="field marg-bot-1">
            <%= f.password_field :password, autocomplete: "off", class: 'form-control register-password', required: true, placeholder: "Password", id: "register-password" %>
            <i class="fa fa-fw fa-lock after" aria-hidden="true"></i>
          </div>

          <div class="field">
            <%= f.password_field :password_confirmation, autocomplete: "off", class: 'form-control', required: true, placeholder: "Confirm password" %>
            <i class="fa fa-fw fa-unlock after" aria-hidden="true"></i>
          </div>

          <div class="actions">
            <%= f.submit "Sign up", class: 'btn btn-purple full-width' %>
          </div>
        <% end %>

        <div class="links">
          Already have an account? <%= link_to "Login here.", new_user_session_path %>
        </div>
      </div>
    </div>
  </div>
</div>