config/routes.rb
Rails.application.routes.draw do
  # general page routes
  root 'welcome#index'
  get '/terms', to: 'welcome#terms_and_conditions', as: 'terms'
  get '/privacy', to: 'welcome#privacy_policy', as: 'privacy'
  get '/perfume', to: 'welcome#perfume', as: 'perfume_overview'

  # routes for posts
  resources :posts

  # routes for discovery boxes
  resources :discovery_boxes, path: '/discovery-box'
  post '/discovery-box/:id/perfumes/:perfume_id', to: 'discovery_boxes#add_perfume', as: 'add_perfume'
  delete '/discovery-box/:id/perfumes/:perfume_id', to: 'discovery_boxes#remove_perfume', as: 'remove_perfume'

  # resources for perfumes
  scope '/admin' do
    resources :perfumes
  end

  # other admin routes
  get '/admin', to: 'admin#panel_home', as: 'panel'
  get '/admin/posts', to: 'admin#manage_posts', as: 'manage_posts'
  get '/admin/users', to: 'admin#manage_users', as: 'manage_users'

  # user show page
  get '/users/:id', to: 'users#show', as: 'user'
  post '/users/:id/refer', to: 'users#refer', as: 'refer'

  # devise links for users
  devise_for :users, controllers: {registrations: 'registrations'}, path: '', path_names: { sign_in: 'login', sign_out: 'logout', password: 'password', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: '' }

  # contact form
  resources :contacts, only: [:new, :create]

  # unique registration links
  devise_scope :user do
    get 'register/:id', to: 'registrations#new', as: 'new_referral'
    post 'register/:id', to: 'registrations#create', as: 'create_referral'
  end

  # 404 error
  get '*unmatched_route', to: 'welcome#not_found', as: 'not_found'
end

app/models/perfume.rb
class Perfume < ApplicationRecord
  # Image attachement for the perfume
  has_attached_file :image, styles: { medium: "500x500>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  # Text validations
  validates :name, presence: true
  validates :characteristics, presence: true
  validates :body, presence: true

  # Relationship to users
  has_many :box_perfume_relationships, dependent: :destroy
  has_many :users, through: :box_perfume_relationships
end

app/controllers/perfumes_controller.rb
class PerfumesController < ApplicationController
  # Ensure that an admin is logged in
  before_action :correct_admin, only: [:new, :edit, :update, :destroy, :index]

  # View all perfumes
  def index
    @perfumes = Perfume.all
  end

  # Render form to create a new perfume
  def new
    @perfume = Perfume.new
  end

  # Create a new perfume
  def create
    @perfume = Perfume.new(perfume_params)

    if @perfume.save
      flash[:notice] = "Perfume created successfully"
      redirect_to perfumes_path
    else
      flash[:alert] = "There was an issue creating the perfume"
      render "new"
    end
  end

  # View form to edit a perfume
  def edit
    @perfume = Perfume.find(params[:id])
  end

  # Update a perfume's information
  def update
    @perfume = Perfume.find(params[:id])

    if @perfume.update(perfume_params)
      flash[:notice] = "Perfume updated successfully"
      redirect_to perfumes_path
    else
      flash[:alert] = "There was an error updating the perfume"
      render 'edit'
    end
  end

  # Delete a perfume
  def destroy
    @perfume = Perfume.find(params[:id])
    @perfume.destroy
    flash[:notice] = "Perfume deleted successfully"
    redirect_to perfumes_path
  end

  private

  # Allow only certain parameters
  def perfume_params
    params.require(:perfume).permit(:name, :characteristics, :body, :image)
  end

  # Only an admin can access routes relating to perfumes
  def correct_admin
    unless current_user and current_user.isAdmin
      flash[:alert] = "Admin access only"
      redirect_to(root_url)
    end
  end
end

app/helpers/perfumes_helper.rb
module PerfumesHelper
end

app/views/perfumes/_form.html.erb
<%= form_for @perfume, html: { multipart: true } do |f| %>
  <% if @perfume.errors.any? %>
    <div class="alert alert-danger" id="error_explanation">
      <h4>
        <%= pluralize(@perfume.errors.count, "error") %> prohibited
        this perfume from being saved:
      </h4>
      <ul>
        <% @perfume.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_field :name, placeholder: "Name", required: true, class: 'border form-control', autofocus: true %>
  <%= f.text_field :characteristics, placeholder: "Characteristics", required: true, class: 'border form-control' %>
  <%= f.text_area :body, placeholder: "Body...", required: true, class: 'border form-control' %>

  <label>
    Perfume image
  </label>
  <%= f.file_field :image %>

  <div class="space-2"></div>

  <%= f.submit "Submit Perfume", class: "btn btn-purple" %>
<% end %>

app/views/perfumes/_perfumes.html.erb
<% @perfumes = Perfume.all %>

<div class="container-fluid marg-top-2 marg-bot-2 marg-wide">
  <div class="row">
    <div class="col-12">
      <div class="space-1 hidden-md-down"></div>
      <h2 class="marg-bot-2 accent-text bold center-mobile">
        Meet your perfumes
      </h2>

      <!-- Render the perfumes -->
      <div id="perfumes" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner" role="listbox">
          <!-- Render each perfume -->
          <% @perfumes.each_with_index do |p, index| %>
            <div class="<%= index == 0 ? "carousel-item active" : "carousel-item" %>">
              <div class="container">
                <div class="row">
                  <div class="col-12 col-md-10 offset-md-1 col-lg-8 offset-lg-2">
                    <div class="flex">
                      <div class="image-wrapper">
                        <% if p.image.file? %>
                          <%= image_tag p.image.url, class: "img" %>
                        <% end %>
                      </div>
                      <div class="content">
                        <div class="space-2"></div>
                        <div class="space-4 hidden-md-down"></div>
                        <div class="space-2 hidden-lg-down"></div>
                        <h3 class="accent-text bold">
                          <%= p.name %>
                        </h3>
                        <p class="characteristics">
                          <%= p.characteristics %>
                        </p>
                        <p>
                          <%= p.body %>
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <!-- Render the links to toggle different perfumes -->
  <ul class="perfume-list">
    <% @perfumes.each_with_index do |p, index| %>
      <li class="<%= index == 1 ? "perfume-item active" : "perfume-item" %>" value="<%= index %>">
        <%= p.name %>
      </li>
    <% end %>
  </ul>
</div>

app/views/perfumes/edit.html.erb
<head>
    <% title 'Love Sylvie | Edit Perfume' %>
    <% description "Edit an existing perfume" %>
</head>

<div class="container-fluid">
  <div class="row">
    <%= render "/shared/admin-sidebar" %>
    <div class="col-12 col-md-8 col-lg-6">
      <h2 class="bold marg-bot-1 marg-top-1">
        Edit perfume
      </h2>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/perfumes/index.html.erb
<head>
    <% title 'Love Sylvie | Perfumes' %>
</head>

<div class="container-fluid">
  <div class="row">
    <%= render '/shared/admin-sidebar' %>
    <div class="col-12 col-md-8 col-lg-6">
      <div class="space-1"></div>
      <h2 class="bold marg-bot-1">
        Listing all perfumes
      </h2>
      <p>
        Here, you can manage the perfumes that users see on this site. Note that only administrators have access to this page, and any changes are effective immediately.
      </p>
      <%= link_to "Add New Perfume", new_perfume_path, class: "btn btn-outline-purple marg-bot-1" %>
      <% @perfumes.each do |p| %>
        <div class="row perfume">
          <div class="push-4 col-4 push-md-0 col-md-3 col-lg-2">
            <% if p.image.file? %>
              <%= image_tag p.image.url, class: "img-fluid" %>
            <% end %>
          </div>
          <div class="col-12 col-md-9 col-lg-10">
            <h4 class="bold">
              <%= p.name %>
            </h4>
            <p class="characteristics">
              <%= p.characteristics %>
            </p>
            <p>
              <%= p.body %>
            </p>
            <%= link_to "Edit", edit_perfume_path(p), class: "btn btn-info btn-sm white-text" %>
            <%= link_to "Delete", p, method: :delete, class: "btn btn-danger btn-sm white-text" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/perfumes/new.html.erb
<head>
  <% title 'Love Sylvie | New Perfume' %>
  <% description "Create a new perfume" %>
</head>

<div class="container-fluid">
  <div class="row">
    <%= render "/shared/admin-sidebar" %>
    <div class="col-12 col-md-8 col-lg-6">
      <h2 class="bold marg-bot-1 marg-top-1">
        Create a new perfume
      </h2>
      <%= render 'form' %>
    </div>
  </div>
</div>