config/routes.rb
Rails.application.routes.draw do
  # general page routes
  root 'welcome#index'
  get '/terms', to: 'welcome#terms_and_conditions', as: 'terms'
  get '/privacy', to: 'welcome#privacy_policy', as: 'privacy'
  get '/perfume', to: 'welcome#perfume', as: 'perfume_overview'

  # routes for posts
  resources :posts

  # routes for discovery boxes
  resources :discovery_boxes, path: '/discovery-box'
  post '/discovery-box/:id/perfumes/:perfume_id', to: 'discovery_boxes#add_perfume', as: 'add_perfume'
  delete '/discovery-box/:id/perfumes/:perfume_id', to: 'discovery_boxes#remove_perfume', as: 'remove_perfume'

  # resources for perfumes
  scope '/admin' do
    resources :perfumes
  end

  # other admin routes
  get '/admin', to: 'admin#panel_home', as: 'panel'
  get '/admin/posts', to: 'admin#manage_posts', as: 'manage_posts'
  get '/admin/users', to: 'admin#manage_users', as: 'manage_users'

  # user show page
  get '/users/:id', to: 'users#show', as: 'user'
  post '/users/:id/refer', to: 'users#refer', as: 'refer'

  # devise links for users
  devise_for :users, controllers: {registrations: 'registrations'}, path: '', path_names: { sign_in: 'login', sign_out: 'logout', password: 'password', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: '' }

  # contact form
  resources :contacts, only: [:new, :create]

  # unique registration links
  devise_scope :user do
    get 'register/:id', to: 'registrations#new', as: 'new_referral'
    post 'register/:id', to: 'registrations#create', as: 'create_referral'
  end

  # 404 error
  get '*unmatched_route', to: 'welcome#not_found', as: 'not_found'
end

app/models/discovery_box.rb
class DiscoveryBox < ApplicationRecord
  belongs_to :user

  # Set up relationship with perfumes
  has_many :box_perfume_relationships, dependent: :destroy
  has_many :perfumes, through: :box_perfume_relationships
end

app/controllers/discovery_boxes_controller.rb
class DiscoveryBoxesController < ApplicationController
  before_action :check_logged_in
  before_action :correct_user, only: [:show, :add_perfume, :edit, :update, :destroy]

  # Redirect the user to their own discovery box
  def index
    # Find the current user's discovery box
    box = current_user.discovery_box

    # Check if the box exists or not
    if box.nil?
      box = current_user.discovery_box.build
      if box.save
        # If the box saves / is created, redirect to it
        redirect_to box
      else
        # If the box does not save for whatever reason
        flash[:alert] = 'Failed to create your discovery box'
        redirect_to root_path
      end
    else
      # If the user has a box, redirect to it
      redirect_to box
    end
  end

  # Show an individual box
  def show
    @box = current_user.discovery_box
    @perfumes = Perfume.all - @box.perfumes
  end

  # def new
  # end

  # Create a new discovery box
  def create
    @box = current_user.discovery_box.build(discovery_box_params)
    if @box.save
      # If the box saves
      flash[:notice] = "Discovery box created successfully"
      redirect_to @box
    else
      # If the box does not save
      flash[:alert] = "There was an issue creating your discovery box"
      redirect_to root_path
    end
  end

  # Add a perfume to the discovery box
  def add_perfume
    # Find the perfume with the passed in ID
    perfume = Perfume.find(params[:perfume_id])

    # If the perfume was deleted / the request was improper
    if (perfume.nil?)
      flash[:alert] = "Perfume not found"
      redirect_to discovery_box_path
      return
    end

    # Isolate the current user's discovery box
    box = current_user.discovery_box

    # Check if the relationship is already in place or if the box is full
    if box.perfumes.length >= 5
      flash[:alert] = "Your box is already full"
      redirect_to box
    elsif box.perfumes.exists?(perfume.id)
      flash[:alert] = "That perfume is alread in your box"
      redirect_to box
    else
      # Create the needed relationship
      box.box_perfume_relationships.build(perfume: perfume, discovery_box: box)

      # Attempt to save
      if box.save
        flash[:notice] = 'Added perfume successfully'
        redirect_to box
      else
        flash[:alert] = 'There was an issue adding the perfume'
        redirect_to box
      end
    end
  end

  # Remove a perfume from the discovery box
  def remove_perfume
    # Find the perfume with the passed in ID
    perfume = Perfume.find(params[:perfume_id])

    # If the perfume was deleted / the request was improper
    if (perfume.nil?)
      flash[:alert] = 'Perfume not found'
      redirect_to discovery_box_path
      return
    end

    # Isolate the current user's discovery box
    box = current_user.discovery_box

    if box.perfumes.exists?(perfume.id)
      # Find the linking record
      relationship = box.box_perfume_relationships.where(discovery_box_id: box.id, perfume_id: perfume.id).first
      relationship.destroy
      flash[:notice] = 'Perfume removed from your box'
      redirect_to box
    else
      flash[:alert] = 'Perfume is not in your discovery box'
      redirect_to discovery_box_path
    end
  end

  # def edit
  #   # TODO?
  # end

  def update
    if @box.update(post_params)
      flash[:notice] = "Discovery box updated successfully"
      redirect_to @box
    else
      flash[:alert] = "There was an error updating your discovery box"
      render 'edit'
    end
  end

  # def destroy
  #   @box.destroy
  #   flash[:notice] = "Discovery box deleted successfully"
  #   redirect_to discovery_box_path
  # end

  private

  def discovery_box_params
    params.require(:discovery_box).permit(:title)
  end

  # ensure that the user is logged in before performing any
  # discovery box action
  def check_logged_in
    unless current_user
      flash[:alert] = "You must be logged in to create a discovery box"
      redirect_to root_path
    end
  end

  # ensure the current user is equal to the user
  def correct_user
    @box = DiscoveryBox.find(params[:id])
    unless @box.user == current_user
      flash[:alert] = "You can only access your own discovery boxes"
      redirect_to root_path
    end
  end
end

app/helpers/discovery_box_helper.rb
module DiscoveryBoxHelper
end

app/views/discovery_boxes/_form.html.erb
<%= form_for @box do |f| %>
  <% if @box.errors.any? %>
    <div class="alert alert-danger" id="error_explanation">
      <h4>
        <%= pluralize(@box.errors.count, "error") %> prohibited
        this discovery box from being saved:
      </h4>
      <ul>
        <% @box.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <label>
    Title
  </label>
  <%= f.text_field :title, placeholder: "Title...", required: true, class: 'form-field form-control', autofocus: true, id: "title" %>

  <!-- <label>
    Perfumes
  </label>
  <% @perfumes.each do |p| %>
    <%= f.fields_for :perfumes do |perfume| %>
      <div>
        <%= f.label p.name %>
      </div>
    <% end %>
  <% end %> -->

  <%= f.submit "Submit Discovery Box", class: "btn btn-purple" %>
<% end %>

app/views/discovery_boxes/new.html.erb
<head>
    <% title 'Love Sylvie | New Discovery Box' %>
    <% description "Create a new discovery box" %>
</head>

<div class="container-fluid">
  <div class="row">
    <div class="col-12 col-md-8 push-md-2 col-lg-6 push-lg-3">
      <h2 class="bold marg-bot-0 marg-top-1">
        Create new discovery box
      </h2>
      <div class="line-1"></div>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/discovery_boxes/show.html.erb
<div class="gray-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-12 col-md-10 offset-md-1 col-lg-8 offset-lg-2">
        <div class="space-1 hidden-md-down"></div>
        <div class="col-12 col-md-10 offset-md-1 col-lg-8 offset-lg-2">
          <%= image_tag "discovery-box/#{@box.perfumes.length}.png", class: 'img-fluid' %>
        </div>
        <div class="card pad-2 marg-bot-2">
          <h4>Contained in your box</h4>
          <% if @box.perfumes.empty? %>
            <p class="marg-bot-0">You haven't added any perfumes to your box yet. Select some from the list below.</p>
          <% else %>
            <% @box.perfumes.each do |p| %>
              <div class="row perfume">
                <div class="push-4 col-4 push-md-0 col-md-3 col-lg-2">
                  <% if p.image.file? %>
                    <%= image_tag p.image.url, class: "img-fluid" %>
                  <% end %>
                </div>
                <div class="col-12 col-md-9 col-lg-10">
                  <h4 class="bold">
                    <%= p.name %>
                  </h4>
                  <p class="characteristics">
                    <%= p.characteristics %>
                  </p>
                  <p>
                    <%= p.body %>
                  </p>
                  <%= link_to remove_perfume_path(@box, p), method: :delete do %>
                    <div class="btn btn-purple btn-sm">
                      Remove from box
                    </div>
                  <% end %>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>

        <div class="card pad-2 marg-bot-2">
          <div class="space-1"></div>
          <% if @perfumes.nil? or @perfumes.empty? %>
            <p class="marg-bot-0">All perfumes are in your box!</p>
          <% else %>
            <h4>Perfumes not in your box</h4>
            <% @perfumes.each do |p| %>
              <div class="row perfume">
                <div class="push-4 col-4 push-md-0 col-md-3 col-lg-2">
                  <% if p.image.file? %>
                    <%= image_tag p.image.url, class: "img-fluid" %>
                  <% end %>
                </div>
                <div class="col-12 col-md-9 col-lg-10">
                  <h4 class="bold">
                    <%= p.name %>
                  </h4>
                  <p class="characteristics">
                    <%= p.characteristics %>
                  </p>
                  <p>
                    <%= p.body %>
                  </p>
                  <%= link_to add_perfume_path(@box, p), method: :post do %>
                    <div class="btn btn-purple btn-sm">
                      Add to box
                    </div>
                  <% end %>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>